apiVersion: v1
kind: Pod
metadata:
  name: web-nfs
spec:
  containers:
  - image: quay.io/centos/centos:stream9
    name: nginx-container
    command: ['sh', '-c', 'echo "Hello" && sleep 3600']
  #   volumeMounts:
  #   - name: html
  #     mountPath: /usr/share/nginx/html
  # volumes:
  # - name: html
  #   nfs:
  #     server: 192.168.10.15
  #     path: /nas/k8s
  #     readOnly: true
