apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: "mongodb://username:password@mongodb-service:27017"
  # (x) database_url: "mongodb-service:27017"
  # (x) database_url: "mongodb-service"
