kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo
          name: mongodb-container
          ports:
            - containerPort: 27017
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: tensorflow
              topologyKey: kubernetes.io/hostname
