kind: Pod
apiVersion: v1
metadata:
  name: mysanta
spec:
  containers:
    - name: mysanta
      image: nginx:1.15
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      ports:
      - containerPort: 80
  volumes:
    - name: html
      configMap:
        name: myindex
