---
kind: Pod
apiVersion: v1
metadata:
  name: exec-liveness
spec:
  containers:
    - name: liveness
      image: registry.k8s.io/busybox
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 15; rm -f /tmp/healthy; sleep 30
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        periodSeconds: 3