---
kind: Service
apiVersion: v1
metadata:
  name: webapp-clusterip-svc
spec:
  type: ClusterIP
  clusterIP: 10.96.10.10
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80