kind: Service
apiVersion: v1
metadata:
  name: webapp-nodeport-svc
spec:
  type: NodePort
  clusterIP: 10.96.10.10
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
