---
apiVersion: v1
kind: Pod
metadata:
  name: memcached

spec:
  containers:
    - name: memcached-container
      image: memcached
      ports:
        - containerPort: 11211
          protocol: TCP
