kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nginx-sts
spec:
  replicas: 3
  serviceName: "nginx"
  selector:
    matchLabels:
      app: mysts
  template:
    metadata:
      name: nginx-pod
      labels:
        app: mysts
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.14