kind: Deployment
apiVersion: apps/v1
metadata:
  name: green-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      version: green
  template:
    metadata:
      name: green-pod
      labels:
        app: web
        version: green
    spec:
      containers:
        - name: green-container
          image: whatwant/node-web:3.0
          ports:
            - containerPort: 8080
