apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mainui-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      name: apache

  template:
      metadata:
        name: mainui-pod
        labels:
          name: apache
          app: main
          rel: stable
      spec:
        containers:
          - name: mainui-container
            image: httpd:2.2
            ports:
              - containerPort: 80
                protocol: TCP
