apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod
  name: testpod
  namespace: default
spec:
  containers:
  - image: nginx
    name: testpod
    ports:
    - containerPort: 80
      protocol: TCP
  serviceAccountName: pod-viewer
