---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: adminer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      name: adminer-pod
      labels:
        app: adminer
    spec:
      containers:
        - image: adminer
          name: adminer-container
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: adminer-svc
spec:
  type: LoadBalancer
  selector:
    app: adminer
  ports:
    - port: 8080
      targetPort: 8080
